GET http://172.17.0.1:9200/_cat/indices?v
Accept: text/plain
###
GET http://localhost:33306/_cat/indices?v
Accept: text/plain
###
GET http://localhost:9200/_cat/indices?v
Accept: text/plain
###
DELETE localhost:9200/dlmf-macros
###
# Simple search test
GET localhost:9200/dlmf-macros/_search
Content-Type: application/json

{
    "query": {
        "nested": {
            "path": "meta",
            "query": {
                "match": {
                    "meta.description": "(Legendre's) incomplete elliptic integral of the first kind"
                }
            }
        }
    }
}
###
# Simple search test
GET localhost:9200/dlmf-macros/_search
Content-Type: application/json

{
    "query": {
        "bool": {
            "must": [
                {
                    "match_all": {}
                }
            ],
            "filter": {
                "range": {
                    "numberOfOptionalParameters": {
                        "gte": "1"
                    }
                }
            }
        }
    }
}

###
POST localhost:8080/math/analyze
Content-Type: application/json
Accept: application/json

{
    "content": ""
}

###
POST localhost:8080/math/translation
Content-Type: application/json

{
    "requestBody": {
        "cas": "Maple",
        "latex": "x+y"
    }
}

###
GET localhost:8080/moi/getMOIByMD5
Content-Type: application/json

{
    "moi": "okbFpXNoPCdHP06riJ9Ulg==",
    "database": "ARQMath"
}