GET http://localhost:9200/_cat/indices?v
Accept: text/plain
###
DELETE localhost:9200/dlmf-macros
###
# Simple search test
GET localhost:9200/dlmf-macros/_search
Content-Type: application/json

{
    "query": {
        "nested": {
            "path": "meta",
            "query": {
                "match": {
                    "meta.description": "Real part"
                }
            }
        }
    }
}
###
# Simple search test
GET localhost:9200/dlmf-macros/_search
Content-Type: application/json

{
    "query": {
        "bool": {
            "must": [
                {
                    "match_all": {}
                }
            ],
            "filter": {
                "range": {
                    "numberOfOptionalParameters": {
                        "gte": "1"
                    }
                }
            }
        }
    }
}